=== kasutu/open-philippine-routes/libs/registry/src/next/v1/v1.schema.json
{
  "$ref": "#/definitions/City",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "City": {
      "additionalProperties": false,
      "properties": {
        "city": {
          "type": "string"
        },
        "city_type": {
          "enum": [
            "highly_urbanized_city",
            "component_city",
            "municipality"
          ],
          "type": "string"
        },
        "country": {
          "const": "Philippines",
          "type": "string"
        },
        "country_code": {
          "const": "PH",
          "type": "string"
        },
        "island_group": {
          "enum": [
            "Luzon",
            "Visayas",
            "Mindanao"
          ],
          "type": "string"
        },
        "latitude": {
          "type": "number"
        },
        "longitude": {
          "type": "number"
        },
        "postal_code": {
          "type": "string"
        },
        "province": {
          "type": "string"
        },
        "province_code": {
          "type": "string"
        },
        "region": {
          "type": "string"
        },
        "region_code": {
          "type": "string"
        },
        "routes": {
          "items": {
            "$ref": "#/definitions/Route"
          },
          "type": "array"
        }
      },
      "required": [
        "city",
        "city_type",
        "country",
        "country_code",
        "island_group",
        "latitude",
        "longitude",
        "postal_code",
        "province",
        "province_code",
        "region",
        "region_code",
        "routes"
      ],
      "type": "object"
    },
    "Route": {
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string"
        },
        "route_code": {
          "type": "string"
        },
        "waypoints": {
          "items": {
            "$ref": "#/definitions/Waypoint"
          },
          "type": "array"
        }
      },
      "required": [
        "route_code",
        "name",
        "waypoints"
      ],
      "type": "object"
    },
    "Waypoint": {
      "additionalProperties": false,
      "properties": {
        "destination": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "latitude": {
          "type": "number"
        },
        "longitude": {
          "type": "number"
        },
        "sequence": {
          "type": "number"
        },
        "street": {
          "type": "string"
        },
        "sub_locality": {
          "type": "string"
        },
        "sub_locality_type": {
          "enum": [
            "district",
            "barangay"
          ],
          "type": "string"
        }
      },
      "required": [
        "destination",
        "latitude",
        "longitude",
        "sequence",
        "street",
        "sub_locality",
        "sub_locality_type"
      ],
      "type": "object"
    }
  }
}

=== kasutu/open-philippine-routes/libs/registry/src/data/v1/visayas_region-06_iloilo_iloilo-city.json
{
  "country": "Philippines",
  "country_code": "PH",
  "island_group": "Visayas",
  "region": "Western Visayas",
  "region_code": "06",
  "province": "Iloilo",
  "province_code": "0630",
  "city": "Iloilo City",
  "city_type": "highly_urbanized_city",
  "postal_code": "5000",
  "latitude": 10.7202,
  "longitude": 122.5621,
  "routes": [
    {
      "route_code": "03",
      "name": "Ungka to Iloilo City Proper via CPU",
      "waypoints": [
        {
          "sequence": 1,
          "sub_locality": "Jaro",
          "sub_locality_type": "district",
          "street": "ITGSI Terminal",
          "destination": ["Iloilo Transport, General Services, Inc. (ITGSI)"],
          "latitude": 10.746199004367853,
          "longitude": 122.53897981730051
        },
        {
          "sequence": 2,
          "sub_locality": "Jaro",
          "sub_locality_type": "district",
          "street": "Diversion Road",
          "destination": ["Christ the King Memorial Park"],
          "latitude": 10.744848024184208,
          "longitude": 122.5393931135651
        },
        {
          "sequence": 3,
          "sub_locality": "Jaro",
          "sub_locality_type": "district",
          "street": "Lopez Jaena Street",
          "destination": [
            "Carmelite Monastery, Fajardo Subdivision, Iloilo Coliseum (Cockfighting Pit), St. Joseph the Worker Parish, Central Philippine University, Panorama Printing, Inc."
          ],
          "latitude": 10.727428434741867,
          "longitude": 122.55557833623556
        },
        {
          "sequence": 4,
          "sub_locality": "Jaro",
          "sub_locality_type": "district",
          "street": "Rizal Street (Jaro Plaza)",
          "destination": ["Jaro Plaza, Jaro Cathedral, Old Ledesma Mansion"],
          "latitude": 10.723979,
          "longitude": 122.55688199999997
        },
        {
          "sequence": 5,
          "sub_locality": "Jaro",
          "sub_locality_type": "district",
          "street": "E. Lopez Street",
          "destination": [
            "Robinsons Place Jaro, Colegio de San Jose, Montinola Antillean House, Nelly's Garden, Lopez Heritage Mansion, West Visayas State University Medical Center, Iloilo Mission Hospital"
          ],
          "latitude": 10.717757330343986,
          "longitude": 122.56130990310805
        },
        {
          "sequence": 6,
          "sub_locality": "Lapaz",
          "sub_locality_type": "barangay",
          "street": "Luna Street",
          "destination": [
            "West Visayas State University, Iloilo National High School, Iloilo Sports Complex, Western Institute of Technology, St. Clement's Church, Gaisano City Iloilo"
          ],
          "latitude": 10.712442873934307,
          "longitude": 122.56463631994984
        },
        {
          "sequence": 7,
          "sub_locality": "City Proper",
          "sub_locality_type": "district",
          "street": "Bonifacio Drive",
          "destination": [
            "Metro Iloilo Water District, Hall of Justice, The Castle Hotel, Philippine Red Cross, Western Visayas Regional Museum, Museo Iloilo, Iloilo Provincial Capitol, Doane Baptist Church, Atrium Mall, Days Hotel Iloilo"
          ],
          "latitude": 10.703899000000007,
          "longitude": 122.56793700000003
        },
        {
          "sequence": 8,
          "sub_locality": "City Proper",
          "sub_locality_type": "district",
          "street": "Iznart Street",
          "destination": [
            "Cabalum Western College, YMCA, Citadines, Philippine Statistics Authority, Hua Siong College of Iloilo (Main)"
          ],
          "latitude": 10.696489999999997,
          "longitude": 122.569119
        },
        {
          "sequence": 9,
          "sub_locality": "City Proper",
          "sub_locality_type": "district",
          "street": "J.M. Basa Street",
          "destination": [
            "Plazoleta Gay, Calle Real, Old Iloilo City Business District, Museum of Philippine Economic History, Plaza Libertad, San Jose Parish, Iloilo City Hall"
          ],
          "latitude": 10.693804180997091,
          "longitude": 122.57108398427357
        },
        {
          "sequence": 10,
          "sub_locality": "City Proper",
          "sub_locality_type": "district",
          "street": "General Hughes Street",
          "destination": [
            "Department of Budget and Management, Colegio del Sagrado Corazon de Jesus, Securities and Exchange Commission"
          ],
          "latitude": 10.68974160553688,
          "longitude": 122.57659641078584
        },
        {
          "sequence": 11,
          "sub_locality": "City Proper",
          "sub_locality_type": "district",
          "street": "Fort San Pedro Drive",
          "destination": [
            "National Economic and Development Authority, National Bureau of Investigation, Fort San Pedro, DPWH Iloilo City District Engineering Office, DPWH Iloilo 1st District Engineering Office, Police Regional Office VI, DENR, PENRO Iloilo"
          ],
          "latitude": 10.690619051999832,
          "longitude": 122.58235014867734
        },
        {
          "sequence": 12,
          "sub_locality": "City Proper",
          "sub_locality_type": "district",
          "street": "Parola Area",
          "destination": [
            "Iloilo Domestic Port, Port of Iloilo (PPA), City Mall Parola, Guimaras, Iloilo Ferry Terminal"
          ],
          "latitude": 10.692258069890329,
          "longitude": 122.58298879518975
        },
        {
          "sequence": 13,
          "sub_locality": "City Proper",
          "sub_locality_type": "district",
          "street": "Fort San Pedro Drive",
          "destination": [
            "National Economic and Development Authority, National Bureau of Investigation, Fort San Pedro, DPWH Iloilo City District Engineering Office, DPWH Iloilo 1st District Engineering Office, Police Regional Office VI, DENR, PENRO Iloilo"
          ],
          "latitude": 10.689369409836914,
          "longitude": 122.57767560249624
        },
        {
          "sequence": 14,
          "sub_locality": "City Proper",
          "sub_locality_type": "district",
          "street": "Santo Rosario Street",
          "destination": ["Santo Rosario City Health Center"],
          "latitude": 10.692174746944929,
          "longitude": 122.57450201127614
        },
        {
          "sequence": 15,
          "sub_locality": "City Proper",
          "sub_locality_type": "district",
          "street": "Zamora Street",
          "destination": [
            "Government Service Insurance System, Magsaysay Center"
          ],
          "latitude": 10.693873205874368,
          "longitude": 122.57117038409353
        },
        {
          "sequence": 16,
          "sub_locality": "City Proper",
          "sub_locality_type": "district",
          "street": "J.M. Basa Street",
          "destination": [
            "Plazoleta Gay, Calle Real, Old Iloilo City Business District, Museum of Philippine Economic History, Plaza Libertad, San Jose Parish, Iloilo City Hall"
          ],
          "latitude": 10.700772087269002,
          "longitude": 122.56915398996654
        },
        {
          "sequence": 17,
          "sub_locality": "City Proper",
          "sub_locality_type": "district",
          "street": "Iznart Street",
          "destination": [
            "Cabalum Western College, YMCA, Citadines, Philippine Statistics Authority, Hua Siong College of Iloilo (Main)"
          ],
          "latitude": 10.702807280852596,
          "longitude": 122.56814357486371
        },
        {
          "sequence": 18,
          "sub_locality": "City Proper",
          "sub_locality_type": "district",
          "street": "Bonifacio Drive",
          "destination": [
            "Casa Real de Iloilo, Metro Iloilo Water District, Hall of Justice, The Castle Hotel, Philippine Red Cross, Western Visayas Regional Museum, Museo Iloilo, Iloilo Provincial Capitol, Doane Baptist Church, Atrium Mall, Days Hotel Iloilo"
          ],
          "latitude": 10.70753707889213,
          "longitude": 122.56717168352475
        },
        {
          "sequence": 19,
          "sub_locality": "City Proper",
          "sub_locality_type": "district",
          "street": "Luna Street",
          "destination": ["Gaisano City Iloilo"],
          "latitude": 10.709818453950987,
          "longitude": 122.56647019517874
        },
        {
          "sequence": 20,
          "sub_locality": "City Proper",
          "sub_locality_type": "district",
          "street": "Huervana Street",
          "destination": ["Dame Hotel"],
          "latitude": 10.713889801509794,
          "longitude": 122.56388145688464
        },
        {
          "sequence": 21,
          "sub_locality": "City Proper",
          "sub_locality_type": "district",
          "street": "Rizal Street (La Paz)",
          "destination": ["La Paz Public Market"],
          "latitude": 10.721695436388302,
          "longitude": 122.55875394729469
        },
        {
          "sequence": 22,
          "sub_locality": "City Proper",
          "sub_locality_type": "district",
          "street": "Luna Street",
          "destination": [
            "West Visayas State University, Iloilo National High School, Iloilo Sports Complex, Western Institute of Technology, St. Clement's Church"
          ],
          "latitude": 10.724372021859622,
          "longitude": 122.55804289069891
        },
        {
          "sequence": 23,
          "sub_locality": "Jaro",
          "sub_locality_type": "district",
          "street": "E. Lopez Street",
          "destination": [
            "Robinsons Place Jaro, Colegio de San Jose, Montinola Antillean House, Nelly's Garden, Lopez Heritage Mansion, West Visayas State University Medical Center, Iloilo Mission Hospital"
          ],
          "latitude": 10.726611121624046,
